!define tk tài khoản
!define nd người dùng
!define mk mật khẩu
!define sp sản phẩm
!define yc yêu cầu
!define dt đối tượng
!define ht hiển thị
!define tb thông báo
!define sys hệ thống
!define ko không
!define tt tồn tại