@startuml


!include ../common.puml
!include ../style.puml

title cn tl mới

actor User as user
boundary UI as ui
control CategoryController as ctc
control CloudinaryController as cc
entity Category_Repository as cr
database Database as db

note right of user
    adminok
end note

user -> ui : chọn 1 tl & yc cn tl mới
ui --> user : tv form cn tl
user -> ui : điền info tl
ui -> ui: kt các trường info
alt yêu cầu có ảnh
    ui -> cc : upload ảnh tl
    cc -> cc : lưu ảnh vào cloud
    cc --> ctc : trả về url ảnh
else không có ảnh
    ctc -> ctc : cn tl không có ảnh
end

cc -> cr: yc lưu tl mới
cr -> db: insert into categories
db --> cr: trả về tl đã lưu
cr --> ctc: trả về tl đã cn
ctc --> ui: fw kq
ui --> user: tb cn tl thành công


@enduml