@startuml
'https://plantuml.com/sequence-diagram
!include ../common.puml
!include ../style.puml
actor User as usr

boundary RegisterUI as ui
control Authentication_Controller as auth
entity UserRepository as ur
database Db as db



note over usr,ui
Precondition:
- nd đã yêu cầu một OTP
- tk nd tồn tại
- người dùng tại trang quên mật khẩu
end note

usr -> ui: mở login form
usr  <-- ui: hiển thị form

ui -> auth: gửi email yêu cầu đặt lại mật khẩu
auth -> ur: tìm kiếm người dùng theo email
ur -> db: select users table
ur <-- db: raw query result set
ur --> auth: map thành đối tượng người dùng


alt người dùng không tồn tại
    auth -> ui: thông báo người dùng không tồn tại
    ui --> usr: hiển thị thông báo lỗi
else người dùng tồn tại
    auth-> auth: kiểm tra trạng thái người dùng
    alt người dùng chưa xác minh
    auth-> ui: báo lỗi người dùng chưa xác minh
    usr <-- ui : hiển thị thông báo lỗi
    else người dùng đã xác minh
        auth -> auth: kiểm tra OTP hợp lệ
        alt OTP không hợp lệ
        auth -> ui: tb lỗi
        ui --> usr: ht lỗi
        else OTP hợp lệ
            auth -> ur: cập nhật mật khẩu & xóa OTP
            ur -> db: update users table
            ur -> db: delete otp
            return kết quả cập nhật
            ur -> auth: kết quả cập nhật
            auth --> ui: thông báo kết quả cập nhật
            ui --> usr: hiển thị kết quả
        end
    end
end


@enduml