@startuml
!include ../common.puml
!include ../style.puml
actor User as user


boundary UI as ui
control Account_Controller as ct
entity UserRepository as ur
database Database as db

note right of user
Precondition:
    adminok
end note

user -> ui : yc xem ds tk
ui -> ct : fw yc
ct -> ur: yc lấy ds tk theo trang
ur -> db: select from accounts
return kq ds tk đã phân trang

ur --> ct: tv ds tk
ct --> ui: fw kq
ui --> user: ht kq trang now

@enduml