@startuml

!include ../common.puml
!include ../style.puml

title Xóa sản phẩm


actor User as user
boundary UI as ui
control ProductController as pc
control CloudinaryController as cc
entity ProductRepository as pr
database Database as db

note right of user
    adminok
end note

user -> ui : yc xóa 1 sp
ui --> user: yc xác nhận
user -> ui : xác nhận xóa
ui -> pc : fw yc
pc -> pr: yc xóa sp
pr -> db: update products set deleted_at = now()
return ? rows affected

pr --> pc: trả về số sp đã xóa
pc --> ui: thông báo xóa 1 sp thành công
ui --> user: hiển thị kết quả xóa
ui --> user: hiển thị lại danh sách sp

@enduml