@startuml
title Xem danh sách sản phẩm trong kho

!include ../../common.puml
!include ../../style.puml

actor User as user
boundary UI as ui
control ProductController as pc
entity ProductRepository as pr
database Database as db

note right of user
    adminok
end note

user -> ui : yc tìm kiếm mã sp
return các trường có thể tìm kiếm
user-> ui: nhập từ khóa tìm kiếm, nhập các trường khác (tùy chọn)
ui -> pc: fw yc
pc -> pc: tổng hợp các trường cần tìm kiếm
pc -> pr: yc tìm kiếm sp theo trang
pr -> pr: tối ưu truy vấn
pr -> db: select products_items
db --> pr: trả về kq ds sp
pr --> pc: fw kq
pc --> ui: fw kq
ui --> user: ht ds các sản phẩm ở trang hiện tại

@enduml